# Generated by Django 3.0.3 on 2020-02-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePlayers',
            new_name='GamePlayer',
        ),
    ]
