# Generated by Django 3.0.3 on 2020-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0002_auto_20200205_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
