# Generated by Django 3.0.3 on 2020-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0005_auto_20200205_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePlayer',
        ),
    ]
