# Generated by Django 3.0.3 on 2020-02-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0006_delete_gameplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrank.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrank.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='qrank.Played', to='qrank.Player'),
        ),
    ]
