# Generated by Django 3.0.3 on 2020-02-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0009_game_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4',
        ),
        migrations.DeleteModel(
            name='Played',
        ),
    ]
