# Generated by Django 3.0.3 on 2020-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0010_auto_20200206_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ranked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
