# Generated by Django 3.0.3 on 2020-02-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0012_auto_20200206_2120'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Match',
        ),
    ]
