# Generated by Django 3.0.3 on 2020-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0013_auto_20200206_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=100),
        ),
    ]
