# Generated by Django 3.0.3 on 2020-03-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0015_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qrank.Game'),
        ),
        migrations.CreateModel(
            name='PlayerRanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(default=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrank.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrank.Player')),
            ],
        ),
    ]
