# Generated by Django 3.0.3 on 2020-03-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0016_auto_20200311_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerranks',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qrank.Game'),
        ),
    ]
