# Generated by Django 3.0.3 on 2020-03-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrank', '0018_auto_20200316_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerRanks',
            new_name='Rank',
        ),
    ]
